PAGES = [
    # Primeiros passos
    "https://ajuda.infinitepay.io/pt-BR/articles/4844360-quais-sao-as-solucoes-da-infinitepay-para-o-meu-negocio",
    "https://ajuda.infinitepay.io/pt-BR/articles/7913300-como-comecar-a-vender-com-a-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406705-pessoa-fisica-pode-vender-com-a-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/4844473-como-faco-o-meu-cadastro-na-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/5274543-em-quanto-tempo-e-feita-a-analise-do-meu-cadastro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406715-pago-aluguel-para-usar-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3567356-quais-bandeiras-sao-aceitas-para-adquirir-as-solucoes-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406711-como-posso-comprar-uma-maquininha-smart",
    "https://ajuda.infinitepay.io/pt-BR/articles/3567351-quais-modelos-de-maquinas-de-cartao-posso-comprar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3567360-posso-ter-mais-de-uma-maquina-no-mesmo-cnpj",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406774-qual-e-o-prazo-de-entrega-da-maquininha-smart",
    "https://ajuda.infinitepay.io/pt-BR/articles/9680790-quais-sao-as-taxas-da-infinitepay-para-cnpj",
    "https://ajuda.infinitepay.io/pt-BR/articles/9680845-quais-sao-as-taxas-da-infinitepay-para-cpf",
    "https://ajuda.infinitepay.io/pt-BR/articles/3359956-quais-sao-as-taxas-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3570213-quais-sao-as-funcionalidades-do-aplicativo-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/9749367-como-alterar-o-idioma-do-app-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406787-quem-e-a-empresa-por-tras-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/10591956-sou-da-imprensa-como-falar-com-a-infinitepay",

    # Nosso suporte
    "https://ajuda.infinitepay.io/pt-BR/articles/3932003-como-funciona-o-atendimento-por-chat-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3932012-a-infinitepay-realiza-atendimentos-por-e-mail",
    "https://ajuda.infinitepay.io/pt-BR/articles/3932036-como-posso-dar-uma-sugestao-de-melhoria-para-a-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3932014-quais-sao-as-redes-sociais-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3932016-qual-e-o-reclame-aqui-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406982-quais-sao-os-canais-oficiais-da-infinitepay",

    # Seus acessos
    "https://ajuda.infinitepay.io/pt-BR/articles/3406803-esqueci-meu-usuario-como-recuperar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406806-esqueci-minha-senha-como-recuperar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406810-nao-consigo-acessar-minha-conta",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406816-o-que-fazer-em-caso-de-bloqueio-de-conta",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406822-posso-usar-a-mesma-conta-em-varios-dispositivos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406826-como-sair-de-um-dispositivo",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406831-posso-usar-o-app-em-mais-de-um-celular",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406835-como-ativar-a-autenticacao-de-dois-fatores",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406840-recebi-um-codigo-de-acesso-sem-solicitar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406844-o-que-fazer-quando-o-token-nao-funciona",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406849-como-revogar-o-acesso-de-um-dispositivo",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406852-dicas-de-seguranca-para-o-acesso",

    # Seu cadastro
    "https://ajuda.infinitepay.io/pt-BR/articles/3406861-como-atualizar-meus-dados-cadastrais",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406865-quais-documentos-sao-necessarios-para-o-cadastro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406870-como-alterar-minha-razao-social",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406874-como-alterar-meu-endereco",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406879-como-alterar-minha-conta-bancaria",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406883-posso-usar-conta-de-terceiros",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406888-por-que-meu-cadastro-foi-reprovado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406892-quando-preciso-atualizar-meu-cadastro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406896-cadastro-como-microempreendedor-individual-mei",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406900-cadastro-como-autonomo",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406904-cadastro-como-empresa-ltda",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406909-cadastro-como-associacao",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406914-como-adicionar-socios-ao-cadastro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406919-posso-ter-mais-de-um-cnpj",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406923-o-que-e-analise-de-risco",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406928-quanto-tempo-leva-a-validacao-do-cadastro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406933-o-que-e-o-questionario-de-idoneidade",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406938-como-alterar-email-cadastrado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406943-posso-usar-email-de-terceiros",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406948-como-excluir-minha-conta",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406952-politica-de-privacidade-e-lgpd",

    # Seus recebimentos
    "https://ajuda.infinitepay.io/pt-BR/articles/3406959-como-funciona-o-prazo-de-recebimento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406963-quais-sao-as-opcoes-de-prazo-de-recebimento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406967-como-alterar-o-prazo-de-recebimento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406972-quando-recebo-minhas-vendas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406976-posso-antecipar-meus-recebimentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406980-quanto-custa-antecipar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406985-como-fazer-a-antecipacao",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406990-quando-a-antecipacao-e-creditada",
    "https://ajuda.infinitepay.io/pt-BR/articles/3406995-por-que-minha-antecipacao-nao-caiu",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407000-o-que-e-parcela-nao-paga",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407005-o-que-e-retencao-de-recebimentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407010-por-que-meus-recebimentos-foram-retidos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407015-quando-a-retencao-e-liberada",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407020-como-consultar-meus-recebimentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407025-como-entender-meu-extrato-de-recebimentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407030-como-ver-meus-recebimentos-no-app",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407035-como-funciona-o-recebimento-parcelado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407040-por-que-meu-recebimento-esta-diferente",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407045-como-funciona-o-repasse-de-taxas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407050-como-verificar-se-houve-cancelamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407055-o-que-e-estorno",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407060-como-funciona-o-chargeback",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407065-quais-sao-os-motivos-de-chargeback",

    # Suas vendas
    "https://ajuda.infinitepay.io/pt-BR/articles/3407070-como-realizar-uma-venda-na-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407075-como-realizar-venda-no-aplicativo",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407080-como-realizar-venda-com-link-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407085-como-funciona-a-venda-digitada",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407090-posso-vender-sem-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407095-como-parcelar-minhas-vendas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407100-qual-o-limite-de-parcelamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407105-como-funciona-o-parcelamento-com-juros",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407110-o-que-e-parcelamento-sem-juros",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407115-como-funciona-o-pagamento-por-aproximacao",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407120-como-funciona-o-pagamento-com-chip",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407125-como-funciona-o-pagamento-com-tarja",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407130-o-que-fazer-quando-uma-venda-e-cancelada",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407135-o-que-fazer-quando-o-cartao-nao-passa",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407140-como-consultar-o-historico-de-vendas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407145-como-enviar-comprovante-de-venda",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407150-como-reimprimir-comprovante",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407155-como-estornar-uma-venda",

    # Sua Maquininha
    "https://ajuda.infinitepay.io/pt-BR/articles/3407160-como-ligar-e-desligar-a-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407165-como-carregar-a-bateria",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407170-quanto-tempo-dura-a-bateria",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407175-como-conectar-a-rede-wi-fi",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407180-como-conectar-a-rede-4g",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407185-como-configurar-o-chip",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407190-a-maquininha-tem-bluetooth",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407195-como-conectar-com-o-celular",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407200-como-funciona-a-impressora",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407205-como-trocar-o-papel-da-impressora",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407210-como-fazer-um-teste-de-impressao",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407215-como-atualizar-o-software-da-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407220-como-resetar-a-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407225-o-que-fazer-quando-a-maquininha-trava",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407230-o-que-fazer-quando-a-maquininha-nao-liga",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407235-o-que-fazer-quando-a-maquininha-sem-sinal",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407240-o-que-fazer-quando-nao-imprime",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407245-o-que-fazer-quando-o-cartao-nao-e-lido",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407250-como-funciona-o-menu-da-maquininha",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407255-como-configurar-atalhos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407260-como-verificar-versao-do-software",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407265-como-funciona-o-relatorio-x",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407270-como-funciona-o-relatorio-z",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407275-posso-usar-a-maquininha-em-outro-estado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407280-o-que-fazer-em-caso-de-perda-ou-roubo",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407285-a-maquininha-tem-garantia",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407290-como-solicitar-suporte-tecnico",

    # Vendas Online
    "https://ajuda.infinitepay.io/pt-BR/articles/3407295-o-que-e-o-link-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407300-como-criar-um-link-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407305-como-enviar-o-link-para-o-cliente",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407310-como-consultar-links-criados",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407315-como-cancelar-um-link",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407320-como-funciona-o-link-com-parcelamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407325-o-que-e-qr-code-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407330-como-gerar-um-qr-code",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407335-como-consultar-pagamentos-por-qr-code",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407340-o-que-e-cobrar-por-assinatura",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407345-como-criar-uma-assinatura",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407350-como-gerenciar-assinaturas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407355-o-que-e-checkout-online",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407360-como-integrar-o-checkout-no-site",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407365-o-que-e-api-de-pagamentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407370-como-gerar-token-de-api",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407375-como-testar-a-api",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407380-o-que-e-webhook",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407385-como-configurar-webhook",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407390-como-validar-retorno-da-api",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407395-como-integrar-com-loja-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407400-o-que-e-marketplace",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407405-como-cadastrar-sellers-no-marketplace",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407410-como-gerenciar-marketplace",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407415-o-que-e-split-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407420-como-funciona-o-split",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407425-como-consultar-splits",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407430-quais-sao-os-status-de-pagamentos-online",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407435-como-receber-alertas-de-status",

    # Equipe e estoque
    "https://ajuda.infinitepay.io/pt-BR/articles/3407440-como-adicionar-usuarios-na-conta",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407445-como-gerenciar-permissoes-de-usuarios",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407450-como-remover-um-usuario",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407455-como-acompanhar-vendas-por-usuario",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407460-como-gerenciar-equipes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407465-o-que-e-controle-de-estoque",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407470-como-cadastrar-produtos-no-estoque",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407475-como-consultar-estoque",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407480-como-alterar-quantidade-de-produto",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407485-como-gerar-relatorio-de-estoque",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407490-como-controlar-estoque-em-tempo-real",

    # Apoio para o seu negócio
    "https://ajuda.infinitepay.io/pt-BR/articles/3407495-o-que-e-gestao-financeira-no-app",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407500-como-acompanhar-minhas-despesas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407505-como-gerar-relatorio-financeiro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407510-o-que-e-controle-de-caixa",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407515-como-usar-o-controle-de-caixa",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407520-como-configurar-metas-de-venda",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407525-como-monitorar-minhas-metas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407530-o-que-e-gestao-de-clientes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407535-como-cadastrar-clientes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407540-como-consultar-clientes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407545-como-enviar-promocoes-aos-clientes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407550-o-que-e-programa-de-fidelidade",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407555-como-criar-programa-de-fidelidade",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407560-como-monitorar-o-programa",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407565-como-funciona-o-suporte-para-negocios",

    # Pix InfinitePay
    "https://ajuda.infinitepay.io/pt-BR/articles/3407570-o-que-e-o-pix-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407575-como-cadastrar-chave-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407580-quais-tipos-de-chave-sao-aceitos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407585-como-receber-com-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407590-como-fazer-transferencia-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407595-como-funciona-o-pix-qr-code",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407600-como-gerar-qr-code-estatico",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407605-como-gerar-qr-code-dinamico",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407610-como-consultar-pagamentos-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407615-como-funciona-o-pix-troco",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407620-como-funciona-o-pix-saque",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407625-o-que-e-pix-agendado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407630-como-criar-pix-agendado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407635-como-cancelar-pix-agendado",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407640-como-funciona-o-pix-copia-e-cola",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407645-quais-sao-os-limites-do-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407650-como-aumentar-o-limite-do-pix",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407655-como-funciona-o-pix-noturno",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407660-como-ativar-o-pix-noturno",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407665-o-que-fazer-se-o-pix-nao-compensar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407670-como-funciona-o-estorno-no-pix",

    # Cartão Virtual Inteligente
    "https://ajuda.infinitepay.io/pt-BR/articles/3407675-o-que-e-o-cartao-virtual-inteligente",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407680-como-criar-um-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407685-como-usar-o-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407690-como-excluir-um-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407695-como-alterar-limite-do-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407700-como-consultar-faturas-do-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407705-o-que-fazer-em-caso-de-fraude-no-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407710-cartao-virtual-funciona-para-assinaturas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407715-cartao-virtual-funciona-em-compras-internacionais",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407720-cartao-virtual-pode-ser-usado-em-lojas-fisicas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407725-como-atualizar-dados-do-cartao-virtual",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407730-como-funciona-o-cancelamento-de-compras-no-cartao-virtual",

    # InfiniteTap
    "https://ajuda.infinitepay.io/pt-BR/articles/3407735-o-que-e-o-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407740-como-ativar-o-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407745-quais-aparelhos-sao-compativeis-com-o-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407750-como-realizar-venda-com-o-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407755-como-funciona-o-pagamento-por-aproximacao-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407760-como-consultar-vendas-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407765-o-que-fazer-se-o-infinitetap-nao-funcionar",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407770-como-atualizar-o-app-para-usar-o-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407775-posso-usar-o-infinitetap-sem-internet",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407780-como-funciona-o-estorno-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407785-como-funciona-a-taxa-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407790-quais-bandeiras-sao-aceitas-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407795-como-funciona-o-comprovante-no-infinitetap",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407800-o-que-fazer-em-caso-de-fraude-no-infinitetap",

    # Documentos e extratos
    "https://ajuda.infinitepay.io/pt-BR/articles/3407805-como-gerar-extrato-de-vendas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407810-como-baixar-comprovante-de-pagamento",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407815-como-enviar-extrato-para-contabilidade",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407820-o-que-e-demonstrativo-financeiro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407825-como-consultar-demonstrativo-financeiro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407830-como-gerar-documento-fiscal",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407835-como-consultar-documentos-gerados",

    # Guia de segurança
    "https://ajuda.infinitepay.io/pt-BR/articles/3407840-como-manter-segura-sua-conta",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407845-como-identificar-golpes-comuns",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407850-o-que-fazer-em-caso-de-fraude",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407855-como-proteger-seus-dados-pessoais",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407860-como-funciona-a-lgpd",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407865-como-denunciar-golpes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407870-como-funciona-a-autenticacao-de-dois-fatores",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407875-o-que-e-phishing",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407880-como-evitar-phishing",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407885-o-que-e-engineering-social",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407890-como-se-proteger-de-engineering-social",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407895-o-que-e-ransomware",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407900-como-evitar-ransomware",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407905-como-funciona-a-criptografia-no-app",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407910-como-funciona-o-monitoramento-de-fraudes",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407915-quais-sao-os-contatos-oficiais-da-infinitepay",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407920-como-identificar-contatos-falsos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407925-o-que-fazer-em-caso-de-contato-falso",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407930-como-funciona-o-suporte-seguro",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407935-dicas-de-seguranca-para-vendas",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407940-dicas-de-seguranca-para-recebimentos",
    "https://ajuda.infinitepay.io/pt-BR/articles/3407945-como-manter-seu-dispositivo-seguro"
]
